### PR TITLE
Options to hide search, favourites and/or power buttons on the home screen

### PR DESCRIPTION
**Pull request by rinkeb**
Hi Max,

I created options to hide the search, favourites and/or power buttons on the home screen. 
Implemented english and (an attempt to :-)) german string resources.

We discussed this on the XBMC forum in http://forum.xbmc.org/showthread.php?tid=103001&pid=1113414#pid1113414

### CODE REVIEW

**Comment by mad-max** [comment]
Patch looks good so far...thanks!
Will merge later on after deciding if a new version will come the next days...

**Comment by rinkeb** [comment]
I noticed that some dutch localisations were missing and partly incorrect. 
While being there anyway, i took the liberty of fixing.. Hope you like it.

The english localisation file is in the commit because of an apparently incorrect string id.

**Comment by mad-max** [comment]
One word: awesome!
Thanks for your help!

**Comment by mad-max** [comment]
Ok, so I think new version should be online the next 2 days...

cheers,
Max

**Comment by mad-max** [comment]
Me again...
After merging and preparing for the new version I found something that needs improvement...
the rss bar is too short if the buttons are disabled...
You're interested in fixing this? 
I think this should be something like 
width=500 if skin.has setting(nopower)
width=600 if !skin.has setting(nopower)

**Comment by rinkeb** [comment]
Ah yes, didn't see it because its disabled. 
I'll try to, but don't know exactly when i will have time. Maybe tomorrow.

**Comment by mad-max** [comment]
Don't hurry...
Next update will need quite a while...also ok if this is done the next 2 weeks...

**Pull request merged**
